name = "EnergyModelsBase"
uuid = "5d7e687e-f956-46f3-9045-6f5a5fd49f50"
authors = ["Lars Hellemo <Lars.Hellemo@sintef.no>, Julian Straus <Julian.Straus@sintef.no>"]
version = "0.8.0"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
TimeStruct = "f9ed5ce0-9f41-4eaa-96da-f38ab8df101c"

[weakdeps]
EnergyModelsInvestments = "fca3f8eb-b383-437d-8e7b-aac76bb2004f"

[extensions]
EMIExt = "EnergyModelsInvestments"

[compat]
JuMP = "^0.23, 1"
julia = "^1.6"
TimeStruct = "^0.8"
EnergyModelsInvestments = "0.7"
